config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles
  resources :companies
  resources :rants
  resources :comments
  resources :categories
  resources :rants do 
    member do 
      put "like", to: "rants#upvote"
      put "dislike", to: "rants#downvote"
    end
  end 
  root 'rants#index'
  get 'theranters' => 'dashboard#ranters'
  get 'dashboard' => 'dashboard#index'
  get 'profile/:id' => 'users#show'
  get 'profile/:id/edit' => 'users#edit'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :rants
         has_many :comments
         belongs_to :company
         mount_uploader :avatar, AvatarUploader

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController 
  before_action :categories

# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :categories

	def show 
		@user = User.find(params[:id])

	end
	def edit 
		if current_user
		@user = User.find(params[:id])
		else 
		redirect_to root_path
		end
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		redirect_to user_path

	end
	private

	def user_params
		params.require(:user).permit(:firstname, :lastname, :username, :userbio, :userwebsite, :userfacebook, :usertwitter, :company_name, :status, :userlinkedin, :avatar)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->

<% if current_user %>
<div class="body-wrapper">
	<div class="edit-header">
	<h3>Edit Profile</h3>
</div>
<%= form_for @user do |f| %>
	<p><%= f.label 'Profile Picture:' %></p>
	<%= f.file_field :avatar %>
	<hr>
	<p><%= f.label 'Status' %></p>
	<%= f.text_field :status %>
	<hr>
	<div class="row">
		<div class="col-md-4"
	<p><%= f.label 'First Name' %></p>
    <%= f.text_field  :firstname %>
</div>
<div class="col-md-4">
    <p><%= f.label 'Last Name' %></p>
    <%= f.text_field :lastname %><br>
</div>
</div>
    <hr>
    <div class="row">
    <div class="col-md-4">
    <p><%= f.label 'Username' %></p>
	<%= f.text_field :username %>
</div>
<div class="col-md-4">
	<p><%= f.label 'Bio' %></p>
	<%= f.text_area :userbio %><br>
</div>
</div>
	<hr>
	<p><%= f.label 'Company' %></p>
	<%= f.text_field :company_name %><br>
	<hr>
	<div class="row">
		<div class="col-md-4">
	<p><%= f.label 'Website' %></p>
	<%= f.text_field :userwebsite %>
</div>
<div class="col-md-4">
	<p><%= f.label 'Facebook' %></p>
	<%= f.text_field :userfacebook %>
</div>
</div>
<br>
<div class="row">
	<div class="col-md-4">
	<p><%= f.label 'Twitter' %></p>
	<%= f.text_field :usertwitter %>
</div>
<div class="col-md-4">
	<p><%= f.label 'Linkedin' %></p>
	<%= f.text_field :userlinkedin %>
</div>
</div>
	<hr>
    <p><%= f.submit "Update" %></p>
 <%end%>
</div>
<% end %>

app/views/users/show.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<div class="body-wrapper">
	<div class="row">
		<div class="profile-top">
			<% if @user.avatar? %>
			<%= image_tag @user.avatar.url, :class => 'profile-image' %>
			<% else %>
			<%= image_tag ('profile.jpg'), :class => 'profile-image' %>
			<% end %>
			<h2><%= @user.username %></h2>
			<% if @user.status === nil %>
			<p>Hello, I am new here</p>
			<% else %>
			<p><%= @user.status %></p>
			<% end %>
		</div>
	</div>
	<hr>
	<div class="row profile-headers">

	<div class="col-md-6">
		<h3>Name: </h3>
		<p><%= @user.firstname %> <%= @user.lastname %></p>
	</div>
	<div class="col-md-6">
		<h3>Company: </h3>
		<p><%= @user.company_name %></p>
	</div>
		<div class="col-md-6">
		<h3>Bio: </h3>
		<p><%= @user.userbio %></p>
	</div>
			<div class="col-md-6">
		<h3>Email: </h3>
		<p><%= @user.email %></p>
	</div>
	</div>
	<hr>
	<div class="row">
		<div class="profile-headers center">
		<h3>Contact</h3>
		</div>
		<a class="website-button" target="_blank"  href="<%= @user.userwebsite %>">Visit Website</a>
		<a target="_blank" href="<%= @user.userfacebook %>"><%= image_tag('facebook.png') %></a> 
		<a target="_blank" href="<%= @user.usertwitter %>"><%= image_tag('twitter.png') %></a> 
		<a target="_blank" href="<%= @user.userlinkedin %>"><%= image_tag('linkedin.png') %></a> 
	</div>
	<% if current_user === @user %>
	<hr>
	<div class="button-edit">
		<%= link_to 'Edit Profile', edit_user_path(@user.id) %>
	</div>
	<% end  %>
</div>