config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles
  resources :companies
  resources :rants
  resources :comments
  resources :categories
  resources :rants do 
    member do 
      put "like", to: "rants#upvote"
      put "dislike", to: "rants#downvote"
    end
  end 
  root 'rants#index'
  get 'theranters' => 'dashboard#ranters'
  get 'dashboard' => 'dashboard#index'
  get 'profile/:id' => 'users#show'
  get 'profile/:id/edit' => 'users#edit'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :rants
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :rant
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :rants
	has_many :comments
	has_many :users
	has_many :likes
	has_many :liked_things
end

app/models/rant.rb
class Rant < ActiveRecord::Base
	belongs_to :category
	validates :category_id, presence: true
	has_many :comments
	belongs_to :user
	acts_as_votable
	mount_uploader :rantpic, RantpicUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :rants
         has_many :comments
         belongs_to :company
         mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?




  def index
  	@categories = Category.all
  end

  def show 
  	@categories = Category.all
  end


  def categories
  	@categories = Category.all
  end
   helper_method :categories


  private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :categories

    def index 
    	@category = Category.all
    	@rants = Rant.all.order("created_at DESC").limit(50)
    end 

    def new
      if current_user.admin == true 
        @category = Category.new
      else
        redirect_to root_path
      end
    end

    
    def edit
        @category = Category.find(params[:id])
    end

    def show 
    	@category = Category.find(params[:id])

    end

    def create
      @category = Category.new(category_params)

      if @category.save
        flash[:notice] = "Saved successfully"
        redirect_to new_category_path
      else
        flash[:error] = "There were errors"
        render :action => :new
      end
      #redirect_to @category
    end

    def update
      @category = Category.find(params[:id])

      #if @category.update(params[:category].permit(:category_params))
      #  redirect_to @category
      #else
      #  render 'edit'
      #end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy

      #redirect_to categorys_path
    end

    private
      def category_params
        params.require(:category).permit(:title, :description)
      end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.save

		redirect_to rant_path(@comment.rant)
	end
	def index
		@comment = Comment.all
	end


	def show 
		@comment = Comment.find(params[:id])
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :user_id, :rant_id)
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :categories
	def index
		@user = current_user
		if @user.company_id != nil 
		@companies = Company.find(params[:id])
		@company = @companies.user_id == current_user.id
		else
			redirect_to new_company_path
		end
	end

	def show
		@company = Company.find(params[:id])
	end

	def new
		if user_signed_in?
	    	@company = Company.new
	    else
	        redirect_to new_user_session_path
	    end
	end

	def create 
		@company = Company.new(company_params)
		@comapny.user_id = current_user.id
		if @company.save
			redirect_to company_path(@company)
		end
	end

	def edit
		if user_signed_in?
			@company = Company.find(params[:id])
				if @company.user_id == current_user.id
					@company = Company.find(params[:id])
				else
					redirect_to root_path
				end
		else
			redirect_to new_user_session_path
		end

	end

	private

	def company_params
		params.require(:company).permit(:name, :logo, :description, :website, :facebook, :twitter, :linkedin, :email, :user_id)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :categories
	def index
		if current_user.admin == true 
			@users = User.all
		else
			redirect_to root_path
		end
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
    before_filter :categories
	def index
		@rants = Rant.includes(:comments).order("created_at desc").limit(4)
        @category = Category.all
        @rant = Rant.find_by(verbum: true)
        @comments = Comment.all
        @rantp = Rant.order("comments_count DESC").limit(25)
	end
	def show 
    	@rants = Rant.find(params[:id])
    	@category = @rants.comments
        @user = @rants.user
        @comments = @rants.comments
        @comment = Comment.new
    end

    def new
    if user_signed_in?
        @category_options = Category.all.map{|c| [ c.title, c.id] }
    	@rant = Rant.new
    else
        redirect_to new_user_registration_path
    end
    end
    def upvote
        @rant = Rant.find(params[:id])
        @rant.upvote_by current_user
        redirect_to rant_path(@rant)
    end
    def downvote
        @rant = Rant.find(params[:id])
        @rant.downvote_by current_user
        redirect_to rant_path(@rant)
    end
    def create 
        @category = Category.all
        @rant = Rant.new(rant_params)
        @rant.user = current_user
        if @rant.save
            flash[:notice] = "Rant Successfully Heard"
            redirect_to @rant
        else
            flash[:error] = ":( not saved"
                render :new
        end
    end
    private
    def rant_params
        params.require(:rant).permit(:title, :body, :category_id, :rantpic)
    end
end

app/controllers/socializations_controller.rb
class SocializationsController < ApplicationController
	def like
		@rant = Rant.find(params[:id])
		current_user.like!(@rant)
		redirect_to rant_path(@rant)
	end

	def unlike
		@rant = Rant.find(params[:id])
		current_user.unlike!(@rant)
		redirect_to rant_path(@rant)
	end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :categories

	def show 
		@user = User.find(params[:id])

	end
	def edit 
		if current_user
		@user = User.find(params[:id])
		else 
		redirect_to root_path
		end
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		redirect_to user_path

	end
	private

	def user_params
		params.require(:user).permit(:firstname, :lastname, :username, :userbio, :userwebsite, :userfacebook, :usertwitter, :company_name, :status, :userlinkedin, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :url => { :action => "add" }  do |f|  %>
    <%= f.text_field  :title %>
    <%= f.text_area :body %>
    <%= f.submit "Add Category" %>
 <%end%>

app/views/categories/new.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<div class="body-wrapper">
	<div class="rant-form">
		<div class="form-header">
			<h3>New Category</h3>
		</div>
<%= form_for @category do |f|  %>
	<%= f.label 'Category Title', :class => 'form-title' %>
    <%= f.text_field  :title, :class => 'title-input' %>
    <%= f.label :description, :class => 'form-title' %>
    <%= f.text_area :description, :class => 'rant-input' %>
    <div class="submit-comment">
    <%= f.submit "Add Category", :class => 'submit-button' %>
</div>
 <%end%>
</div>
</div>

app/views/categories/show.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<div class="body-wrapper">
	<div class="rant-list">
		<% if @category.rants.count < 1 %>
		<div class="rant-notification">
		<h3>Guess nothing to rant about</h3>
	</div>
		<% else %>
<% @category.rants.each do |f| %>
<div class="cat-rant-box">
	<h3><%= f.title %></h3>
	<p class="turncate"><%= f.body %></p>
	<%= link_to "Read More..", rant_path(f.id) %>
	<hr>
	<p>Author: <%= f.user.username %>
</div>
<% end %>
<% end %>
</div>
</div>

app/views/comments/_comment.html.erb
<% for @comment.each do |f| %>
<%= @comment.body %>
<% end %>

app/views/comments/_form.html.erb
<div class="create-comment">
<%= form_for (@comment) do |f| %>
<h3><%= f.label 'Rant On' %></h3>
	<%= f.text_area :body, :class => "textarea-comment" %>
	<%= f.hidden_field :rant_id, :value => @rants.id %>
	<div class="submit-comment"><%= f.submit "Submit", :class => 'submit-but' %></div>
<% end %>
</div>

app/views/companies/index.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<% @company.each do |f| %>
<%= @company.name %>
<% end %>

app/views/companies/new.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->

app/views/companies/show.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<%= @company.name %>
<%= @company.website %>
<%= @company.user_id %>
<%= current_user.id %>

app/views/rants/index.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<div class="body-wrapper">
	<div class="top-section">
	<div class="row">
		<div class="col-md-8">
			<div class="type-section">
				<div class="type-header">
					<p>Most Recent Rants</p>
				</div>
				<div class="rant-list">
				<% if @rants.count === 0 %>
					<div class="rant-notification">
						<h3>There are no rants</h3>
					</div>
				<% else %>
					<% @rants.each do |f| %>
					<div class="rant-box">
						<h3><%= f.title %></h3> 

						<p class="turncate"><%= f.body %></p>
						<p><%= link_to 'Read More..', rant_path(f.id) %></p>
					 <a class="fa fa-comment-o"> <%= f.comments.count %></a> - <%= link_to 'I Feel Ya',like_rant_path(f), method: :put %> <%= f.get_upvotes.size %> - <%= link_to "Naaah", dislike_rant_path(f), method: :put %> <%= f.get_downvotes.size %>
					</div>
					<% end %>
				<% end %>
				</div>
		</div>
	</div>
	<div class="col-md-4 margin-left">
		<div class="type-section">
				<div class="type-header">
					<p>The Stats</p>
				</div>
				<div class="rant-list">
					<div class="stats-box">
						<h3>Rants: <%= @rants.count %></h3>
					</div>
					<div class="stats-box">
						<h3>Comments: <%= @comments.count %></h3>
					</div>
					<div class="stats-box">
						<h3> Users: <%= User.count %></h3>
					</div>
				</div>
			</div>
	</div>
	</div>
	<br>
	<!-- Top Rants -->
	<div class="row">
		<div class="col-md-12">
			<div class="type-section">
				<div class="type-header">
					<p>Top Rants</p>
				</div>
				<div class="rant-list">
				<% if @rantp.count === 0 %>
					<div class="rant-notification">
						<h3>There are no rants</h3>
					</div>
				<% else %>
					<% @rantp.each do |f| %>
						<div class="rant-box">
							<h3><%= f.title %></h3>
							<p class="turncate"><%= f.body %></p>
							<p><%= link_to 'Read More..', rant_path(f.id) %></p>
							<a class="fa fa-comment-o"> <%= f.comments.count %></a> - <%= link_to 'I Feel Ya',like_rant_path(f), method: :put %> <%= f.get_upvotes.size %> - <%= link_to "Naaah", dislike_rant_path(f), method: :put %> <%= f.get_downvotes.size %>
						</div>
					<% end %>
				<% end %>
				</div>
			</div>
		</div>
	</div>
	</div>

</div>
</div>

app/views/rants/new.html.erb
<!-- NAv BAR -->

<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<% if user_signed_in? %>
<div class="body-wrapper">
	<div class="rant-form">
		<div class="form-header">
			<h3>Vent a Rant</h3>
			</div>
<%= form_for @rant do |f|  %>
	<p><%= f.label 'Rant Picture' %></p>
	<%= f.file_field :rantpic %>
	<%= f.label 'Title: ', :class => 'form-title' %>
    <%= f.text_field  :title, :class => 'title-input' %>
    <%= f.label 'Rant Category: ', :class => 'form-title' %>
    <div class="rant-select">
	<%= f.select(:category_id, @category_options) %>
	</div>
	<hr>
    <%= f.label 'Rant:', :class => 'form-title' %>
    <%= f.text_area :body, :class => 'rant-input' %>
	<div class="submit-comment">
    <%= f.submit "Submit Rant", :class => 'submit-button' %>
</div>
 <%end%>

</div>
</div>
<% end %>

app/views/rants/show.html.erb
<!-- NAv BAR -->
<div class="category-bar">
	<div class="categories-content">
	<% @categories.each do |f| %>
		<p><%= link_to f.title, category_path(f), :class => 'category-links' %></p>
	<% end %>
	<p id="menu"><%= image_tag("nav-icon.png", :class => 'nav-icon') %></p>
	</div>
</div>
<!-- Content -->
<div class="body-wrapper">
	<div class="rant-header">
<h3><%= @rants.title %> - <%= link_to 'I Feel Ya',like_rant_path(@rants), method: :put %> <%= @rants.get_upvotes.size %> - <%= link_to "Naaah", dislike_rant_path(@rants), method: :put %> <%= @rants.get_downvotes.size %></h3>
</div>

<div class="rant-body">
<%= @rants.body %>
</div>
<div class="rant-picture">
<p>attachments:</p>
	<a href="<%= image_path @rants.rantpic %>"><%= image_tag @rants.rantpic, :class => 'rant-pic' %></a>
	</div>
<hr>
<div class="rant-author">
<p>Author: <a href="<%= user_path(@user)%>"><%= @user.username %></a> - Created: <%= time_ago_in_words(@rants.created_at)%></p>
</div>
<hr>
<div class="comments-section">
<h2>Comments</h2>
<% if user_signed_in? %>
<%= render 'comments/form' %>
<% end %>
<hr>
<% @comments.each do |f| %>
<div class="comment-box">
<p class="comment-header"><% if f.user.avatar? %><%= image_tag f.user.avatar.url, :class => 'comment-pic' %><% else %><%= image_tag ('profile.jpg'), :class => 'comment-pic' %><%end %>  <%= f.user.username %> - <span style="color: #e3e3e3; font-style: italic;"><%= f.user.status %></span></p>
<p class="timestamp"><%= time_ago_in_words(f.created_at) %></p>
<%= f.body %>

</div>
<% end %>

</div>


</div>