config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles
  resources :companies
  resources :rants
  resources :comments
  resources :categories
  resources :rants do 
    member do 
      put "like", to: "rants#upvote"
      put "dislike", to: "rants#downvote"
    end
  end 
  root 'rants#index'
  get 'theranters' => 'dashboard#ranters'
  get 'dashboard' => 'dashboard#index'
  get 'profile/:id' => 'users#show'
  get 'profile/:id/edit' => 'users#edit'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :rants
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :rant
  belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :rants
	has_many :comments
	has_many :users
	has_many :likes
	has_many :liked_things
end

app/models/rant.rb
class Rant < ActiveRecord::Base
	belongs_to :category
	validates :category_id, presence: true
	has_many :comments
	belongs_to :user
	acts_as_votable
	mount_uploader :rantpic, RantpicUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :rants
         has_many :comments
         belongs_to :company
         mount_uploader :avatar, AvatarUploader

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :categories

    def index 
    	@category = Category.all
    	@rants = Rant.all.order("created_at DESC").limit(50)
    end 

    def new
      if current_user.admin == true 
        @category = Category.new
      else
        redirect_to root_path
      end
    end

    
    def edit
        @category = Category.find(params[:id])
    end

    def show 
    	@category = Category.find(params[:id])

    end

    def create
      @category = Category.new(category_params)

      if @category.save
        flash[:notice] = "Saved successfully"
        redirect_to new_category_path
      else
        flash[:error] = "There were errors"
        render :action => :new
      end
      #redirect_to @category
    end

    def update
      @category = Category.find(params[:id])

      #if @category.update(params[:category].permit(:category_params))
      #  redirect_to @category
      #else
      #  render 'edit'
      #end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy

      #redirect_to categorys_path
    end

    private
      def category_params
        params.require(:category).permit(:title, :description)
      end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.save

		redirect_to rant_path(@comment.rant)
	end
	def index
		@comment = Comment.all
	end


	def show 
		@comment = Comment.find(params[:id])
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :user_id, :rant_id)
	end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :categories
	def index
		@user = current_user
		if @user.company_id != nil 
		@companies = Company.find(params[:id])
		@company = @companies.user_id == current_user.id
		else
			redirect_to new_company_path
		end
	end

	def show
		@company = Company.find(params[:id])
	end

	def new
		if user_signed_in?
	    	@company = Company.new
	    else
	        redirect_to new_user_session_path
	    end
	end

	def create 
		@company = Company.new(company_params)
		@comapny.user_id = current_user.id
		if @company.save
			redirect_to company_path(@company)
		end
	end

	def edit
		if user_signed_in?
			@company = Company.find(params[:id])
				if @company.user_id == current_user.id
					@company = Company.find(params[:id])
				else
					redirect_to root_path
				end
		else
			redirect_to new_user_session_path
		end

	end

	private

	def company_params
		params.require(:company).permit(:name, :logo, :description, :website, :facebook, :twitter, :linkedin, :email, :user_id)
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :categories
	def index
		if current_user.admin == true 
			@users = User.all
		else
			redirect_to root_path
		end
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
    before_filter :categories
	def index
		@rants = Rant.includes(:comments).order("created_at desc").limit(4)
        @category = Category.all
        @rant = Rant.find_by(verbum: true)
        @comments = Comment.all
        @rantp = Rant.order("comments_count DESC").limit(25)
	end
	def show 
    	@rants = Rant.find(params[:id])
    	@category = @rants.comments
        @user = @rants.user
        @comments = @rants.comments
        @comment = Comment.new
    end

    def new
    if user_signed_in?
        @category_options = Category.all.map{|c| [ c.title, c.id] }
    	@rant = Rant.new
    else
        redirect_to new_user_registration_path
    end
    end
    def upvote
        @rant = Rant.find(params[:id])
        @rant.upvote_by current_user
        redirect_to rant_path(@rant)
    end
    def downvote
        @rant = Rant.find(params[:id])
        @rant.downvote_by current_user
        redirect_to rant_path(@rant)
    end
    def create 
        @category = Category.all
        @rant = Rant.new(rant_params)
        @rant.user = current_user
        if @rant.save
            flash[:notice] = "Rant Successfully Heard"
            redirect_to @rant
        else
            flash[:error] = ":( not saved"
                render :new
        end
    end
    private
    def rant_params
        params.require(:rant).permit(:title, :body, :category_id, :rantpic)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :categories

	def show 
		@user = User.find(params[:id])

	end
	def edit 
		if current_user
		@user = User.find(params[:id])
		else 
		redirect_to root_path
		end
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		redirect_to user_path

	end
	private

	def user_params
		params.require(:user).permit(:firstname, :lastname, :username, :userbio, :userwebsite, :userfacebook, :usertwitter, :company_name, :status, :userlinkedin, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">  
	  <title>Publicrant</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application' %>
	  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Tinos:400,700' rel='stylesheet' type='text/css'>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60475368-1', 'auto');
  ga('send', 'pageview');

</script>
<script src="//load.sumome.com/" data-sumo-site-id="49c84683a2fca5c10494b3ef9c6f9a8792f4b6df07e1c8a2111cd19a04330957" async="async"></script>
		<div id="wrapper">
		<!-- Top Navbar -->
		<div class="top-nav">
					<div class="logins-section">
						<% if user_signed_in? %>
							<% if current_user.admin == true %>
								<p><%= link_to 'Dashboard', dashboard_path, :class => 'logins-buttons' %></p>
								<% end %>
						<p><%= link_to 'Post Rant', new_rant_path, :class => 'logins-buttons' %></p>
							<p><%= link_to 'Sign Out', destroy_user_session_path, :class => 'logins-buttons', :method => :delete %></p>
							<p><%= link_to 'My Profile', user_path(current_user.id), :class => 'logins-buttons' %></p>
						<% else %>
							<p><%= link_to 'Login', user_session_path, :class => 'logins-buttons' %></p>
							<p><%= link_to 'Sign Up', new_user_registration_path, :class => 'logins-buttons' %></p>
						<% end %>
					</div>
		</div>
		<div class="navbar">
			<div class="wrapper">
			<div class="row">
				<div class="col-md-4">
					<div class="logo-section">
						<%= link_to image_tag("logo.png", :class => 'logo-image'), root_path %>
					</div>
				</div>
				<div class="col-md-8">
	
				</div>
			</div>
		</div>
	</div>
		<!-- Category Bar -->
	<%= yield %>
<!-- Footer Goes Here -->
<footer class="site-footer">
	<div class="container">
	<p>2014 - Public Rant - Quint Industries - <%= link_to 'The Ranters', theranters_path %></p>
</div>
</footer>
</div>
	</body>
</html>